In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/competitions/playground-series-s6e3/sample_submission.csv
/kaggle/input/competitions/playground-series-s6e3/train.csv
/kaggle/input/competitions/playground-series-s6e3/test.csv

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    classification_report,
    confusion_matrix
)

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

In [3]:
import os

for dirname, _, filenames in os.walk('/kaggle/input'):
    print(dirname)

/kaggle/input
/kaggle/input/competitions
/kaggle/input/competitions/playground-series-s6e3

In [4]:
import pandas as pd

train = pd.read_csv(
    "/kaggle/input/competitions/playground-series-s6e3/train.csv"
)

test = pd.read_csv(
    "/kaggle/input/competitions/playground-series-s6e3/test.csv"
)

sample_submission = pd.read_csv(
    "/kaggle/input/competitions/playground-series-s6e3/sample_submission.csv"
)

print("Train Shape:", train.shape)
print("Test Shape:", test.shape)
print("Sample Submission Shape:", sample_submission.shape)

train.head()

Train Shape: (594194, 21)
Test Shape: (254655, 20)
Sample Submission Shape: (254655, 2)

,id,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,Male,0,Yes,Yes,29,Yes,No,DSL,Yes,...,Yes,Yes,No,No,One year,Yes,Mailed check,60.10,1653.85,No
1,1,Male,0,Yes,Yes,58,Yes,No,DSL,Yes,...,No,Yes,Yes,No,Two year,No,Credit card (automatic),69.50,3778.20,No
2,2,Male,0,Yes,No,58,Yes,Yes,Fiber optic,No,...,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,100.40,5841.35,No
3,3,Female,0,No,No,1,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,69.70,70.70,Yes
4,4,Female,0,No,No,1,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.45,70.45,Yes

In [5]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 594194 entries, 0 to 594193
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                594194 non-null  int64
 1   gender            594194 non-null  object
 2   SeniorCitizen     594194 non-null  int64
 3   Partner           594194 non-null  object
 4   Dependents        594194 non-null  object
 5   tenure            594194 non-null  int64
 6   PhoneService      594194 non-null  object
 7   MultipleLines     594194 non-null  object
 8   InternetService   594194 non-null  object
 9   OnlineSecurity    594194 non-null  object
 10  OnlineBackup      594194 non-null  object
 11  DeviceProtection  594194 non-null  object
 12  TechSupport       594194 non-null  object
 13  StreamingTV       594194 non-null  object
 14  StreamingMovies   594194 non-null  object
 15  Contract          594194 non-null  object
 16  PaperlessBilling  594194 non-null  object
 17  PaymentMethod     594194 non-null  object
 18  MonthlyCharges    594194 non-null  float64
 19  TotalCharges      594194 non-null  float64
 20  Churn             594194 non-null  object
dtypes: float64(2), int64(3), object(16)
memory usage: 95.2+ MB

In [6]:
train.isnull().sum().sort_values(ascending=False).head(20)

id                  0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
dtype: int64

In [7]:
train["Churn"].value_counts(normalize=True)

Churn
No     0.774792
Yes    0.225208
Name: proportion, dtype: float64

In [8]:
train.describe()

,id,SeniorCitizen,tenure,MonthlyCharges,TotalCharges
count,594194.000000,594194.000000,594194.000000,594194.000000,594194.000000
mean,297096.500000,0.114102,36.577258,65.866223,2494.377057
std,171529.177262,0.317936,25.061922,31.067444,2353.916710
min,0.000000,0.000000,1.000000,18.250000,18.800000
25%,148548.250000,0.000000,12.000000,29.900000,639.650000
50%,297096.500000,0.000000,35.000000,74.100000,1433.650000
75%,445644.750000,0.000000,62.000000,90.800000,4263.800000
max,594193.000000,1.000000,72.000000,118.750000,8684.800000

In [9]:
train.head()

,id,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,Male,0,Yes,Yes,29,Yes,No,DSL,Yes,...,Yes,Yes,No,No,One year,Yes,Mailed check,60.10,1653.85,No
1,1,Male,0,Yes,Yes,58,Yes,No,DSL,Yes,...,No,Yes,Yes,No,Two year,No,Credit card (automatic),69.50,3778.20,No
2,2,Male,0,Yes,No,58,Yes,Yes,Fiber optic,No,...,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,100.40,5841.35,No
3,3,Female,0,No,No,1,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,69.70,70.70,Yes
4,4,Female,0,No,No,1,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.45,70.45,Yes

In [10]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 594194 entries, 0 to 594193
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                594194 non-null  int64
 1   gender            594194 non-null  object
 2   SeniorCitizen     594194 non-null  int64
 3   Partner           594194 non-null  object
 4   Dependents        594194 non-null  object
 5   tenure            594194 non-null  int64
 6   PhoneService      594194 non-null  object
 7   MultipleLines     594194 non-null  object
 8   InternetService   594194 non-null  object
 9   OnlineSecurity    594194 non-null  object
 10  OnlineBackup      594194 non-null  object
 11  DeviceProtection  594194 non-null  object
 12  TechSupport       594194 non-null  object
 13  StreamingTV       594194 non-null  object
 14  StreamingMovies   594194 non-null  object
 15  Contract          594194 non-null  object
 16  PaperlessBilling  594194 non-null  object
 17  PaymentMethod     594194 non-null  object
 18  MonthlyCharges    594194 non-null  float64
 19  TotalCharges      594194 non-null  float64
 20  Churn             594194 non-null  object
dtypes: float64(2), int64(3), object(16)
memory usage: 95.2+ MB

In [11]:
test_ids = test["id"]

train.drop("id", axis=1, inplace=True)
test.drop("id", axis=1, inplace=True)

In [12]:
train["Churn"] = train["Churn"].map({
    "No": 0,
    "Yes": 1
})

In [13]:
# Average monthly spending over customer lifetime
train["AvgSpend"] = train["TotalCharges"] / (train["tenure"] + 1)
test["AvgSpend"] = test["TotalCharges"] / (test["tenure"] + 1)

# Long-term customer indicator
train["LongTermCustomer"] = (train["tenure"] > 24).astype(int)
test["LongTermCustomer"] = (test["tenure"] > 24).astype(int)

# High-value customer indicator
train["HighMonthlyCharge"] = (
    train["MonthlyCharges"] > train["MonthlyCharges"].median()
).astype(int)

test["HighMonthlyCharge"] = (
    test["MonthlyCharges"] > test["MonthlyCharges"].median()
).astype(int)

In [14]:
X = train.drop("Churn", axis=1)
y = train["Churn"]

combined = pd.concat([X, test])

combined = pd.get_dummies(
    combined,
    drop_first=True
)

X = combined.iloc[:len(train)]
test_final = combined.iloc[len(train):]

In [15]:
X_train, X_valid, y_train, y_valid = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

In [16]:
model = XGBClassifier(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    eval_metric="auc",
    random_state=42
)

model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='auc', feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=500,
              n_jobs=None, num_parallel_tree=None, ...)

In [17]:
valid_preds = model.predict_proba(X_valid)[:, 1]

score = roc_auc_score(
    y_valid,
    valid_preds
)

print("Validation ROC-AUC:", score)

Validation ROC-AUC: 0.9168434665198141

In [18]:
importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": model.feature_importances_
})

importance = importance.sort_values(
    "Importance",
    ascending=False
)

importance.head(15)

                               Feature  Importance
31      PaymentMethod_Electronic check    0.364898
13         InternetService_Fiber optic    0.245421
28                   Contract_Two year    0.129607
14                  InternetService_No    0.044123
27                   Contract_One year    0.044045
1                               tenure    0.028281
5                     LongTermCustomer    0.026208
15  OnlineSecurity_No internet service    0.016252
24                     StreamingTV_Yes    0.010311
6                    HighMonthlyCharge    0.009504
29                PaperlessBilling_Yes    0.009333
0                        SeniorCitizen    0.008292
26                 StreamingMovies_Yes    0.008249
16                  OnlineSecurity_Yes    0.007310
12                   MultipleLines_Yes    0.006449

In [19]:
test_preds = model.predict_proba(test_final)[:, 1]

submission = pd.DataFrame({
    "id": test_ids,
    "Churn": test_preds
})

submission.to_csv(
    "submission.csv",
    index=False
)

submission.head()

       id     Churn
0  594194  0.092029
1  594195  0.000248
2  594196  0.104329
3  594197  0.004116
4  594198  0.522671